// Generated by scripts/generate-web-commands.mjs. Do not edit by hand.
use crate::AppState;
use crate::coolapk::client::DeviceProfile;
use serde_json::{Value, json};

pub async fn get_index_v8_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_index_v8_feeds(page).await
}

pub async fn get_index_v8_feeds_paged(
    state: &AppState,
    page: u32,
    first_item: String,
    last_item: String,
) -> Result<Value, String> {
    state
        .client
        .get_index_v8_feeds_paged(page, &first_item, &last_item)
        .await
}

pub async fn get_index_v8_entities_paged(
    state: &AppState,
    page: u32,
    first_item: String,
    last_item: String,
) -> Result<Value, String> {
    state
        .client
        .get_index_v8_entities_paged(page, &first_item, &last_item)
        .await
}

pub async fn get_tab_config(state: &AppState) -> Result<Value, String> {
    state.client.get_tab_config().await
}

pub async fn update_home_tab_config(
    state: &AppState,
    config_json: String,
) -> Result<Value, String> {
    state.client.update_home_tab_config(&config_json).await
}

pub async fn get_discovery_config(state: &AppState) -> Result<Value, String> {
    state.client.get_discovery_config().await
}

pub async fn get_discovery_page_data(
    state: &AppState,
    url: String,
    title: String,
    sub_title: String,
    page: u32,
    first_item: String,
    last_item: String,
    page_context: String,
    request_args_json: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_discovery_page_data(
            &url,
            &title,
            &sub_title,
            page,
            &first_item,
            &last_item,
            &page_context,
            request_args_json.as_deref().unwrap_or(""),
        )
        .await
}

pub async fn get_live_detail(state: &AppState, live_id: String) -> Result<Value, String> {
    state.client.get_live_detail(&live_id).await
}

pub async fn get_search_suggestions(
    state: &AppState,
    query: String,
) -> Result<Value, String> {
    state.client.get_search_suggestions(&query).await
}

pub async fn get_topic_detail_v7(state: &AppState, tag: String) -> Result<Value, String> {
    state.client.get_topic_detail_v7(&tag).await
}

pub async fn get_product_detail(
    state: &AppState,
    product_id: String,
) -> Result<Value, String> {
    state.client.get_product_detail(&product_id).await
}

pub async fn get_product_feeds(
    state: &AppState,
    product_id: String,
    feed_type: String,
    list_type: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_product_feeds(&product_id, &feed_type, &list_type, page)
        .await
}

pub async fn get_product_config(
    state: &AppState,
    config_id: String,
) -> Result<Value, String> {
    state.client.get_product_config(&config_id).await
}

pub async fn add_config_compare(
    state: &AppState,
    config_id: String,
) -> Result<Value, String> {
    state.client.add_config_compare(&config_id).await
}

pub async fn remove_config_compare(
    state: &AppState,
    config_id: String,
) -> Result<Value, String> {
    state.client.remove_config_compare(&config_id).await
}

pub async fn get_product_brand_list(state: &AppState) -> Result<Value, String> {
    state.client.get_product_brand_list().await
}

pub async fn get_product_category_list(state: &AppState) -> Result<Value, String> {
    state.client.get_product_category_list().await
}

pub async fn get_product_list(
    state: &AppState,
    url: String,
    title: String,
    sub_title: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_product_list(&url, &title, &sub_title, page, first_item.as_deref().unwrap_or(""), last_item.as_deref().unwrap_or(""))
        .await
}

pub async fn get_product_brand_products(
    state: &AppState,
    brand_id: String,
    brand_type: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_product_brand_products(&brand_id, &brand_type, page, first_item.as_deref().unwrap_or(""), last_item.as_deref().unwrap_or(""))
        .await
}

pub async fn get_secondhand_brand_list(state: &AppState) -> Result<Value, String> {
    state.client.get_secondhand_brand_list().await
}

pub async fn get_secondhand_product_list(
    state: &AppState,
    brand_id: String,
    list_type: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_secondhand_product_list(&brand_id, &list_type, page, first_item.as_deref().unwrap_or(""), last_item.as_deref().unwrap_or(""))
        .await
}

pub async fn get_product_media_list(
    state: &AppState,
    product_id: String,
    media_type: String,
    is_recommend: i32,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_product_media_list(&product_id, &media_type, is_recommend, page)
        .await
}

pub async fn change_product_wish_status(
    state: &AppState,
    product_id: String,
    status: i32,
) -> Result<Value, String> {
    state
        .client
        .change_product_wish_status(&product_id, status)
        .await
}

pub async fn change_product_follow_status(
    state: &AppState,
    product_id: String,
    status: i32,
) -> Result<Value, String> {
    state
        .client
        .change_product_follow_status(&product_id, status)
        .await
}

pub async fn get_product_wish_list(
    state: &AppState,
    product_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_product_wish_list(&product_id, page).await
}

pub async fn get_product_buy_list(
    state: &AppState,
    product_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_product_buy_list(&product_id, page).await
}

pub async fn get_my_product_list(
    state: &AppState,
    uid: String,
    product_type: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_my_product_list(&uid, &product_type, page)
        .await
}

pub async fn get_product_rating_chart(
    state: &AppState,
    product_id: String,
) -> Result<Value, String> {
    state.client.get_product_rating_chart(&product_id).await
}

pub async fn get_product_subtab_feeds(
    state: &AppState,
    product_id: String,
    sub_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_product_subtab_feeds(&product_id, &sub_id, page).await
}

pub async fn create_product_rating(
    state: &AppState,
    product_id: String,
    score: i32,
    message: String,
    buy_status: bool,
) -> Result<Value, String> {
    state.client.create_product_rating(&product_id, score, &message, buy_status).await
}

pub async fn get_product_rating_list(
    state: &AppState,
    product_id: String,
    star: i32,
    is_owner: i32,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_product_rating_list(&product_id, star, is_owner, page)
        .await
}

pub async fn get_apk_rating_user_list(
    state: &AppState,
    apk_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_apk_rating_user_list(&apk_id, page).await
}

pub async fn change_rating_status(
    state: &AppState,
    product_id: String,
    value: i32,
    uid: String,
    buy_status: Option<i32>,
    is_owner: Option<i32>,
) -> Result<Value, String> {
    state
        .client
        .change_rating_status(&product_id, value, &uid, buy_status, is_owner)
        .await
}

pub async fn get_dyh_detail(state: &AppState, dyh_id: String) -> Result<Value, String> {
    state.client.get_dyh_detail(&dyh_id).await
}

pub async fn get_dyh_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_dyh_list(page).await
}

pub async fn get_dyh_feeds(
    state: &AppState,
    dyh_id: String,
    feed_type: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_dyh_feeds(&dyh_id, &feed_type, page).await
}

pub async fn get_event_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_event_list(page).await
}

pub async fn get_event_detail(
    state: &AppState,
    event_id: String,
) -> Result<Value, String> {
    state.client.get_event_detail(&event_id).await
}

pub async fn get_dyh_follow_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_dyh_follow_list(page).await
}

pub async fn get_dyh_subscribe_list(
    state: &AppState,
    page: u32,
) -> Result<Value, String> {
    state.client.get_dyh_subscribe_list(page).await
}

pub async fn get_dyh_editor_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_dyh_editor_list(page).await
}

pub async fn get_user_product_albums(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_user_product_albums(&uid, page).await
}

pub async fn get_goods_list_items(
    state: &AppState,
    uid: String,
    goods_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_goods_list_items(&uid, &goods_id, page).await
}

pub async fn create_product_album(
    state: &AppState,
    title: String,
    description: String,
    album_type: u32,
    target_type: String,
    target_id: String,
    product_items: String,
) -> Result<Value, String> {
    state
        .client
        .create_product_album(
            &title,
            &description,
            album_type,
            &target_type,
            &target_id,
            &product_items,
        )
        .await
}

pub async fn get_node_feeds(
    state: &AppState,
    node_type: String,
    node_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_node_feeds(&node_type, &node_id, page).await
}

pub async fn get_apk_feeds(
    state: &AppState,
    package_name: String,
    sort_type: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_apk_feeds(&package_name, &sort_type, page)
        .await
}

pub async fn get_hot_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_hot_feeds(page).await
}

pub async fn get_rank_feeds(
    state: &AppState,
    rank_type: String,
    page: u32,
    background: Option<bool>,
) -> Result<Value, String> {
    state
        .client
        .get_rank_feeds_with_mode(&rank_type, page, background.unwrap_or(false))
        .await
}

pub async fn get_latest_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_latest_feeds(page).await
}

pub async fn get_digest_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_digest_feeds(page).await
}

pub async fn get_cool_picture_rank(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_cool_picture_rank(page).await
}

pub async fn get_board_feeds(
    state: &AppState,
    board_tag: String,
    page: u32,
    background: Option<bool>,
) -> Result<Value, String> {
    state
        .client
        .get_board_feeds_with_mode(&board_tag, page, background.unwrap_or(false))
        .await
}

pub async fn get_secondhand_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_secondhand_feeds(page).await
}

pub async fn get_hot_topics(state: &AppState) -> Result<Value, String> {
    state.client.get_hot_topics().await
}

pub async fn get_favorite_list(
    state: &AppState,
    fav_type: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_favorite_list(
            &fav_type,
            page,
            first_item.as_deref().unwrap_or(""),
            last_item.as_deref().unwrap_or(""),
        )
        .await
}

pub async fn get_feed_collection_status(
    state: &AppState,
    feed_id: String,
) -> Result<Value, String> {
    state.client.get_feed_collection_status(&feed_id).await
}

pub async fn update_collection_item(
    state: &AppState,
    collection_ids: String,
    cancel_ids: String,
    target_id: String,
    feed_type: String,
    trace: String,
) -> Result<Value, String> {
    state
        .client
        .update_collection_item(
            &collection_ids,
            &cancel_ids,
            &target_id,
            &feed_type,
            &trace,
        )
        .await
}

pub async fn get_collection_list(
    state: &AppState,
    uid: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state.client.get_collection_list(&uid, page, first_item.as_deref().unwrap_or(""), last_item.as_deref().unwrap_or("")).await
}

pub async fn get_collection_item_list(
    state: &AppState,
    collection_id: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_collection_item_list(
            &collection_id,
            page,
            first_item.as_deref().unwrap_or(""),
            last_item.as_deref().unwrap_or(""),
        )
        .await
}

pub async fn get_collection_detail(
    state: &AppState,
    collection_id: String,
) -> Result<Value, String> {
    state.client.get_collection_detail(&collection_id).await
}

pub async fn create_collection(
    state: &AppState,
    title: String,
    description: String,
    cover: String,
    is_open: i32,
    source_id: String,
) -> Result<Value, String> {
    state
        .client
        .create_collection(&title, &description, &cover, is_open, &source_id)
        .await
}

pub async fn update_collection(
    state: &AppState,
    id: String,
    title: String,
    description: String,
    cover: String,
    is_open: i32,
) -> Result<Value, String> {
    state
        .client
        .update_collection(&id, &title, &description, &cover, is_open)
        .await
}

pub async fn delete_collection(state: &AppState, id: String) -> Result<Value, String> {
    state.client.delete_collection(&id).await
}

pub async fn remove_collection_item(
    state: &AppState,
    item_id: String,
) -> Result<Value, String> {
    state.client.remove_collection_item(&item_id).await
}

pub async fn clear_collection_invalid_items(
    state: &AppState,
    collection_id: String,
) -> Result<Value, String> {
    state
        .client
        .clear_collection_invalid_items(&collection_id)
        .await
}

pub async fn follow_collection(
    state: &AppState,
    collection_id: String,
) -> Result<Value, String> {
    state.client.follow_collection(&collection_id).await
}

pub async fn unfollow_collection(
    state: &AppState,
    collection_id: String,
) -> Result<Value, String> {
    state.client.unfollow_collection(&collection_id).await
}

pub async fn like_collection(
    state: &AppState,
    collection_id: String,
) -> Result<Value, String> {
    state.client.like_collection(&collection_id).await
}

pub async fn unlike_collection(
    state: &AppState,
    collection_id: String,
) -> Result<Value, String> {
    state.client.unlike_collection(&collection_id).await
}

pub async fn follow_dyh(state: &AppState, dyh_id: String) -> Result<Value, String> {
    state.client.follow_dyh(&dyh_id).await
}

pub async fn unfollow_dyh(state: &AppState, dyh_id: String) -> Result<Value, String> {
    state.client.unfollow_dyh(&dyh_id).await
}

pub async fn follow_live(state: &AppState, live_id: String) -> Result<Value, String> {
    state.client.follow_live(&live_id).await
}

pub async fn unfollow_live(state: &AppState, live_id: String) -> Result<Value, String> {
    state.client.unfollow_live(&live_id).await
}

pub async fn get_feed_forward_list(
    state: &AppState,
    feed_id: String,
    feed_type: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_feed_forward_list(&feed_id, &feed_type, page)
        .await
}

pub async fn get_feed_like_list(
    state: &AppState,
    feed_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_feed_like_list(&feed_id, page).await
}

pub async fn get_feed_change_history(
    state: &AppState,
    feed_id: String,
) -> Result<Value, String> {
    state.client.get_feed_change_history(&feed_id).await
}

pub async fn search_tags(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_tags(&query, page).await
}

pub async fn follow_tag(state: &AppState, tag: String) -> Result<Value, String> {
    state.client.follow_tag(&tag).await
}

pub async fn unfollow_tag(state: &AppState, tag: String) -> Result<Value, String> {
    state.client.unfollow_tag(&tag).await
}

pub async fn get_device_feed_list(
    state: &AppState,
    tag: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_device_feed_list(&tag, page, first_item.as_deref().unwrap_or(""), last_item.as_deref().unwrap_or(""))
        .await
}

pub async fn get_question_answers(
    state: &AppState,
    feed_id: String,
    sort: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_question_answers(
            &feed_id,
            &sort,
            page,
            first_item.as_deref().unwrap_or(""),
            last_item.as_deref().unwrap_or(""),
        )
        .await
}

pub async fn follow_question(state: &AppState, question_id: String) -> Result<Value, String> {
    state.client.follow_question(&question_id).await
}

pub async fn unfollow_question(state: &AppState, question_id: String) -> Result<Value, String> {
    state.client.unfollow_question(&question_id).await
}

pub async fn invite_question_answer(state: &AppState, question_id: String, uid: String) -> Result<Value, String> {
    state.client.invite_question_answer(&question_id, &uid).await
}

pub async fn get_vote_comments(
    state: &AppState,
    feed_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_vote_comments(&feed_id, page).await
}

pub async fn create_user_vote(
    state: &AppState,
    feed_id: String,
    option_ids: Vec<String>,
    anonymous_status: bool,
) -> Result<Value, String> {
    state
        .client
        .create_user_vote(&feed_id, &option_ids, anonymous_status)
        .await
}

pub async fn get_hit_history(
    state: &AppState,
    page: u32,
    history_type: String,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state.client.get_hit_history(page, &history_type, first_item.as_deref(), last_item.as_deref()).await
}

pub async fn get_recent_history(state: &AppState, page: u32, first_item: Option<String>, last_item: Option<String>) -> Result<Value, String> {
    state.client.get_recent_history(page, first_item.as_deref(), last_item.as_deref()).await
}

pub async fn get_spam_feed_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_spam_feed_list(page).await
}

pub async fn get_hidden_replies(
    state: &AppState,
    feed_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_hidden_replies(&feed_id, page).await
}

pub async fn get_followed_topics(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_followed_topics(page).await
}

pub async fn search_users(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_users(&query, page).await
}

pub async fn get_search_suggestions_app(
    state: &AppState,
    query: String,
) -> Result<Value, String> {
    state.client.get_search_suggestions_app(&query).await
}

pub async fn search_feed_topics(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_feed_topics(&query, page).await
}

pub async fn search_publish_topics(state: &AppState, query: String, page: u32, recent_ids: String) -> Result<Value, String> {
    state.client.search_publish_topics(&query, page, &recent_ids).await
}

pub async fn get_product_versions(state: &AppState, product_id: String) -> Result<Value, String> {
    state.client.get_product_versions(&product_id).await
}

pub async fn get_product_detail_by_name(
    state: &AppState,
    name: String,
) -> Result<Value, String> {
    state.client.get_product_detail_by_name(&name).await
}

pub async fn get_load_config(state: &AppState) -> Result<Value, String> {
    state.client.get_load_config().await
}

pub async fn get_home_tab_config(
    state: &AppState,
    reset: bool,
) -> Result<Value, String> {
    state.client.get_home_tab_config(reset).await
}

pub async fn get_feed_detail(state: &AppState, feed_id: String, post_token: Option<String>, post_token_field: Option<String>) -> Result<Value, String> {
    state.client.get_feed_detail(&feed_id, post_token.as_deref(), post_token_field.as_deref()).await
}

pub async fn get_public_feed_detail(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.get_public_feed_detail(&feed_id).await
}

pub async fn get_editable_feed(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.get_editable_feed(&feed_id).await
}

pub async fn update_feed(state: &AppState, feed_id: String, message: String, pic: String, post_token: Option<String>) -> Result<Value, String> {
    state.client.update_feed(&feed_id, &message, &pic, post_token.as_deref()).await
}

pub async fn resolve_video_url(
    state: &AppState,
    request_params: String,
) -> Result<Value, String> {
    state.client.resolve_video_url(&request_params).await
}

pub async fn resolve_live_photo_video(
    state: &AppState,
    image_url: String,
    content_id: String,
    content_type: String,
) -> Result<Value, String> {
    state
        .client
        .resolve_live_photo_video(&image_url, &content_id, &content_type)
        .await
}

pub async fn get_live_photo_video_header(state: &AppState, video_url: String) -> Result<String, String> {
    state.client.get_live_photo_video_header(&video_url).await
}

pub async fn get_reply_detail(
    state: &AppState,
    reply_id: String,
) -> Result<Value, String> {
    state.client.get_reply_detail(&reply_id).await
}

pub async fn get_feed_replies(
    state: &AppState,
    feed_id: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
    list_type: Option<String>,
    from_feed_author: Option<u32>,
) -> Result<Value, String> {
    state
        .client
        .get_feed_replies_paged(
            &feed_id,
            page,
            first_item.as_deref().unwrap_or(""),
            last_item.as_deref().unwrap_or(""),
            list_type.as_deref().unwrap_or("lastupdate_desc"),
            from_feed_author.unwrap_or(0),
        )
        .await
}

pub async fn get_sub_replies(
    state: &AppState,
    feed_id: String,
    reply_id: String,
    page: u32,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .get_sub_replies_paged(
            &feed_id,
            &reply_id,
            page,
            last_item.as_deref().unwrap_or(""),
        )
        .await
}

pub async fn get_hot_replies(
    state: &AppState,
    feed_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_hot_replies(&feed_id, page).await
}

pub async fn search_all(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_all(&query, page).await
}

pub async fn search_by_type(
    state: &AppState,
    search_type: String,
    query: String,
    page: u32,
    first_item: String,
    last_item: String,
    page_type: String,
    page_param: String,
    feed_type: String,
    sort: String,
    is_strict: u32,
    category: String,
    page_context: String,
) -> Result<Value, String> {
    state
        .client
        .search_by_type(
            &search_type,
            &query,
            page,
            &first_item,
            &last_item,
            &page_type,
            &page_param,
            &feed_type,
            &sort,
            is_strict,
            &category,
            &page_context,
        )
        .await
}

pub async fn get_hot_searches(state: &AppState, refresh: bool) -> Result<Value, String> {
    state.client.get_hot_searches(refresh).await
}

pub async fn search_feeds(
    state: &AppState,
    query: String,
    page: u32,
    sort_type: String,
) -> Result<Value, String> {
    state.client.search_feeds(&query, page, &sort_type).await
}

pub async fn get_user_space(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.get_user_space(&uid).await
}

pub async fn get_public_user_space(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.get_public_user_space(&uid).await
}

pub async fn get_user_profile(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.get_user_profile(&uid).await
}

pub async fn get_public_user_profile(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.get_public_user_profile(&uid).await
}

pub async fn get_user_remark_list(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.get_user_remark_list(&uid).await
}

pub async fn update_user_profile(
    state: &AppState,
    key: String,
    value: String,
) -> Result<Value, String> {
    state.client.update_user_profile(&key, &value).await
}

pub async fn change_avatar(
    state: &AppState,
    image_bytes: Vec<u8>,
    file_name: String,
    content_type: String,
) -> Result<Value, String> {
    state
        .client
        .change_avatar(&image_bytes, &file_name, &content_type)
        .await
}

pub async fn update_user_cover(
    state: &AppState,
    url: String,
) -> Result<Value, String> {
    state.client.update_user_cover(&url).await
}

pub async fn get_user_qr_image(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.get_user_qr_image(&uid).await
}

pub async fn get_user_follow_nodes(
    state: &AppState,
    uid: String,
) -> Result<Value, String> {
    state.client.get_user_follow_nodes(&uid).await
}

pub async fn get_user_forum_follow_list(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_user_forum_follow_list(&uid, page).await
}

pub async fn get_user_feeds(
    state: &AppState,
    uid: String,
    page: u32,
    feed_type: String,
) -> Result<Value, String> {
    state.client.get_user_feeds(&uid, page, &feed_type).await
}

pub async fn get_user_like_list(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_user_like_list(&uid, page).await
}

pub async fn get_user_tab_data(
    state: &AppState,
    uid: String,
    tab: String,
    page: u32,
    first_item: String,
    last_item: String,
    rating_target: String,
) -> Result<Value, String> {
    state
        .client
        .get_user_tab_data(
            &uid,
            &tab,
            page,
            &first_item,
            &last_item,
            &rating_target,
        )
        .await
}

pub async fn get_topic_detail(state: &AppState, tag: String) -> Result<Value, String> {
    state.client.get_topic_detail(&tag).await
}

pub async fn get_topic_feeds(
    state: &AppState,
    tag: String,
    page: u32,
    list_type: String,
    first_item: String,
    last_item: String,
    block_status: i32,
) -> Result<Value, String> {
    state
        .client
        .get_topic_feeds(&tag, page, &list_type, &first_item, &last_item, block_status)
        .await
}

pub async fn get_topic_tab_data(
    state: &AppState,
    url: String,
    title: String,
    sub_title: String,
    page: u32,
    first_item: String,
    last_item: String,
    page_context: String,
) -> Result<Value, String> {
    state
        .client
        .get_topic_tab_data(&url, &title, &sub_title, page, &first_item, &last_item, &page_context)
        .await
}

pub async fn get_topic_hub_data(
    state: &AppState,
    sub_url: String,
    page: u32,
    first_item: String,
    last_item: String,
) -> Result<Value, String> {
    state
        .client
        .get_topic_hub_data(&sub_url, page, &first_item, &last_item)
        .await
}

pub async fn get_app_detail(
    state: &AppState,
    package_name: String,
) -> Result<Value, String> {
    state.client.get_app_detail(&package_name).await
}

pub async fn get_apk_comments(
    state: &AppState,
    app_id: String,
    list_type: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_apk_comments(&app_id, &list_type, page)
        .await
}

pub async fn get_notification_count(state: &AppState) -> Result<Value, String> {
    state.client.get_notification_count().await
}

pub async fn clear_notification_count(
    state: &AppState,
    notification_type: String,
) -> Result<Value, String> {
    state.client.clear_notification_count(&notification_type).await
}

pub async fn get_notifications(
    state: &AppState,
    notification_type: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_notifications(&notification_type, page)
        .await
}

pub async fn list_messages(state: &AppState, page: u32, first_item: String, last_item: String) -> Result<Value, String> {
    state.client.list_messages(page, &first_item, &last_item).await
}

pub async fn get_recent_chat_users(
    state: &AppState,
    page: u32,
) -> Result<Value, String> {
    state.client.get_recent_chat_users(page).await
}

pub async fn list_chat_history(
    state: &AppState,
    ukey: String,
    page: u32,
    first_item: Option<String>,
    last_item: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .list_chat_history(&ukey, page, first_item.as_deref().unwrap_or(""), last_item.as_deref().unwrap_or(""))
        .await
}

pub async fn delete_message_chat(
    state: &AppState,
    ukey: String,
) -> Result<Value, String> {
    state.client.delete_message_chat(&ukey).await
}

pub async fn send_private_message(
    state: &AppState,
    uid: String,
    message: String,
) -> Result<Value, String> {
    state.client.send_private_message(&uid, &message).await
}

pub async fn send_private_image(
    state: &AppState,
    uid: String,
    message_pic: String,
) -> Result<Value, String> {
    state.client.send_private_image(&uid, &message_pic).await
}

pub async fn read_message(state: &AppState, ukey: String) -> Result<Value, String> {
    state.client.read_message(&ukey).await
}

pub async fn favorite_feed(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.favorite_feed(&feed_id).await
}

pub async fn unfavorite_feed(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.unfavorite_feed(&feed_id).await
}

pub async fn favorite_apk(
    state: &AppState,
    package_name: String,
) -> Result<Value, String> {
    state.client.favorite_apk(&package_name).await
}

pub async fn unfavorite_apk(
    state: &AppState,
    package_name: String,
) -> Result<Value, String> {
    state.client.unfavorite_apk(&package_name).await
}

pub async fn delete_feed(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.delete_feed(&feed_id).await
}

pub async fn delete_reply(state: &AppState, reply_id: String) -> Result<Value, String> {
    state.client.delete_reply(&reply_id).await
}

pub async fn create_forward(
    state: &AppState,
    feed_id: String,
    message: String,
    pic: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .create_forward(&feed_id, &message, pic.as_deref())
        .await
}

pub async fn upload_image(
    state: &AppState,
    image_bytes: Vec<u8>,
    file_name: String,
    content_type: String,
    dir: String,
    to_uid: Option<String>,
    live_video_bytes: Option<Vec<u8>>,
    hdr: Option<u32>,
) -> Result<Value, String> {
    state
        .client
        .upload_image_with_live(
            &image_bytes,
            &file_name,
            &content_type,
            &dir,
            to_uid.as_deref(),
            live_video_bytes.as_deref(),
            hdr.unwrap_or(0),
        )
        .await
}

pub async fn get_black_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_black_list(page).await
}

pub async fn get_ignore_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_ignore_list(page).await
}

pub async fn get_limit_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_limit_list(page).await
}

pub async fn add_to_black_list(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.add_to_black_list(&uid).await
}

pub async fn remove_from_black_list(
    state: &AppState,
    uid: String,
) -> Result<Value, String> {
    state.client.remove_from_black_list(&uid).await
}

pub async fn add_to_ignore_list(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.add_to_ignore_list(&uid).await
}

pub async fn remove_from_ignore_list(
    state: &AppState,
    uid: String,
) -> Result<Value, String> {
    state.client.remove_from_ignore_list(&uid).await
}

pub async fn get_apk_url(
    state: &AppState,
    package_name: String,
) -> Result<Value, String> {
    state.client.get_apk_url(&package_name).await
}

pub async fn get_apk_qr(state: &AppState, package_name: String) -> Result<Value, String> {
    state.client.get_apk_qr(&package_name).await
}

pub async fn like_feed(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.like_feed(&feed_id).await
}

pub async fn unlike_feed(state: &AppState, feed_id: String) -> Result<Value, String> {
    state.client.unlike_feed(&feed_id).await
}

pub async fn like_reply(state: &AppState, reply_id: String) -> Result<Value, String> {
    state.client.like_reply(&reply_id).await
}

pub async fn unlike_reply(state: &AppState, reply_id: String) -> Result<Value, String> {
    state.client.unlike_reply(&reply_id).await
}

pub async fn reply_feed(
    state: &AppState,
    feed_id: String,
    message: String,
    rid: Option<String>,
    pic: Option<String>,
    post_token: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .reply_feed(
            &feed_id,
            &message,
            rid.as_deref(),
            pic.as_deref(),
            post_token.as_deref(),
        )
        .await
}

pub async fn comment_apk(
    state: &AppState,
    app_id: String,
    message: String,
) -> Result<Value, String> {
    state.client.comment_apk(&app_id, &message).await
}

pub async fn follow_user(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.follow_user(&uid).await
}

pub async fn unfollow_user(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.unfollow_user(&uid).await
}

pub async fn special_follow_user(
    state: &AppState,
    uid: String,
    special: bool,
) -> Result<Value, String> {
    state.client.special_follow_user(&uid, special).await
}

pub async fn cancel_follower(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.cancel_follower(&uid).await
}

pub async fn update_user_remark(
    state: &AppState,
    uid: String,
    name: String,
) -> Result<Value, String> {
    state.client.update_user_remark(&uid, &name).await
}

pub async fn get_following_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_following_feeds(page).await
}

pub async fn get_follow_user_list(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_follow_user_list(&uid, page).await
}

pub async fn get_fans_user_list(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_fans_user_list(&uid, page).await
}

pub async fn create_feed(
    state: &AppState,
    message: String,
    pic: Option<String>,
    post_token: Option<String>,
    options: Option<crate::coolapk::client::PublishOptions>,
) -> Result<Value, String> {
    state
        .client
        .create_feed_with_options(&message, pic.as_deref(), post_token.as_deref(), options.as_ref())
        .await
}

pub async fn create_answer(
    state: &AppState,
    question_id: String,
    message: String,
    pic: Option<String>,
    post_token: Option<String>,
) -> Result<Value, String> {
    state
        .client
        .create_answer(
            &question_id,
            &message,
            pic.as_deref(),
            post_token.as_deref(),
        )
        .await
}

pub fn get_device_info(state: &AppState) -> Result<Value, String> {
    state.client.get_device_info()
}

pub fn clear_user_cookie(state: &AppState) -> Result<String, String> {
    state.client.clear_user_cookie()?;
    Ok("登录状态已清除".to_string())
}

pub async fn list_accounts(state: &AppState) -> Result<Value, String> {
    state.client.list_accounts().await
}

pub async fn login_as(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.login_as(&uid).await
}

pub async fn save_account(
    state: &AppState,
    uid: String,
    username: String,
    user_avatar: String,
    cookie: String,
) -> Result<Value, String> {
    state
        .client
        .save_account(&uid, &username, &user_avatar, &cookie)
        .await
}

pub async fn persist_current_account(
    state: &AppState,
    uid: String,
    username: String,
    user_avatar: String,
) -> Result<Value, String> {
    state
        .client
        .persist_current_account(&uid, &username, &user_avatar)
        .await
}

pub async fn remove_account(state: &AppState, uid: String) -> Result<Value, String> {
    state.client.remove_account(&uid).await
}

pub async fn login_by_account(
    state: &AppState,
    account: String,
    password: String,
) -> Result<Value, String> {
    state.client.login_by_account(&account, &password).await
}

pub async fn send_sms_vcode(state: &AppState, mobile: String) -> Result<Value, String> {
    state.client.send_sms_vcode(&mobile).await
}

pub async fn login_by_mobile(
    state: &AppState,
    mobile: String,
    vcode: String,
) -> Result<Value, String> {
    state.client.login_by_mobile(&mobile, &vcode).await
}

pub async fn get_game_list(
    state: &AppState,
    page: u32,
    game_type: String,
) -> Result<Value, String> {
    state.client.get_game_list(page, &game_type).await
}

pub async fn search_apks(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_apks(&query, page).await
}

pub async fn search_games(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_games(&query, page).await
}

pub async fn get_app_list(
    state: &AppState,
    page: u32,
    cat: String,
) -> Result<Value, String> {
    state.client.get_app_list(page, &cat).await
}

pub async fn get_album_list(
    state: &AppState,
    list_type: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_album_list(&list_type, page).await
}

pub async fn search_albums(
    state: &AppState,
    query: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_albums(&query, page).await
}

pub async fn get_album_detail(
    state: &AppState,
    album_id: String,
) -> Result<Value, String> {
    state.client.get_album_detail(&album_id).await
}

pub async fn get_user_album_list(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_user_album_list(&uid, page).await
}

pub async fn create_album(
    state: &AppState,
    title: String,
    intro: String,
    cover: String,
) -> Result<Value, String> {
    state.client.create_album(&title, &intro, &cover).await
}

pub async fn edit_album(
    state: &AppState,
    album_id: String,
    title: String,
    intro: String,
    cover: String,
) -> Result<Value, String> {
    state.client.edit_album(&album_id, &title, &intro, &cover).await
}

pub async fn add_album_apk(
    state: &AppState,
    album_id: String,
    package_name: String,
    title: String,
    url: String,
    note: String,
    display_order: i32,
    logo: String,
) -> Result<Value, String> {
    state
        .client
        .add_album_apk(&album_id, &package_name, &title, &url, &note, display_order, &logo)
        .await
}

pub async fn delete_album_apk(
    state: &AppState,
    album_id: String,
    package_name: String,
) -> Result<Value, String> {
    state.client.delete_album_apk(&album_id, &package_name).await
}

pub async fn get_album_replies(
    state: &AppState,
    album_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_album_replies(&album_id, page).await
}

pub async fn get_headline_feeds(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_headline_feeds(page).await
}

pub async fn get_update_list(state: &AppState, page: u32) -> Result<Value, String> {
    state.client.get_update_list(page).await
}

pub async fn get_editor_choice_feeds(
    state: &AppState,
    page: u32,
) -> Result<Value, String> {
    state.client.get_editor_choice_feeds(page).await
}

pub async fn get_apk_discoverers(
    state: &AppState,
    package_name: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_apk_discoverers(&package_name, page).await
}

pub async fn get_apk_recommend_list(
    state: &AppState,
    apk_type: String,
    title: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_apk_recommend_list(&apk_type, &title, page)
        .await
}

pub async fn get_apk_related_apps(
    state: &AppState,
    package_name: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_apk_related_apps(&package_name, page)
        .await
}

pub async fn get_apk_gift_list(
    state: &AppState,
    apk_id: Option<String>,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .get_apk_gift_list(apk_id.as_deref(), page)
        .await
}

pub async fn get_download_version_list(
    state: &AppState,
    package_name: String,
) -> Result<Value, String> {
    state.client.get_download_version_list(&package_name).await
}

pub async fn get_picture_list(
    state: &AppState,
    tag: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_picture_list(&tag, page).await
}

pub async fn get_user_rating_list(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_user_rating_list(&uid, page).await
}

pub async fn search_apks_by_developer(
    state: &AppState,
    developer: String,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .search_apks_by_developer(&developer, page)
        .await
}

pub async fn search_apks_by_tag(
    state: &AppState,
    tag: String,
    apk_type: String,
    page: u32,
) -> Result<Value, String> {
    state.client.search_apks_by_tag(&tag, &apk_type, page).await
}

pub async fn get_goods_search_hot_words(state: &AppState) -> Result<Value, String> {
    state.client.get_goods_search_hot_words().await
}

pub async fn search_goods(
    state: &AppState,
    keyword: String,
    sort_name: String,
    sort: String,
    is_coupon: u32,
    page: u32,
) -> Result<Value, String> {
    state
        .client
        .search_goods(&keyword, &sort_name, &sort, is_coupon, page)
        .await
}

pub async fn prepare_goods_by_url(state: &AppState, url: String) -> Result<Value, String> {
    state.client.prepare_goods_by_url(&url).await
}

pub async fn get_goods_detail(
    state: &AppState,
    goods_id: String,
) -> Result<Value, String> {
    state.client.get_goods_detail(&goods_id).await
}

pub async fn get_goods_list_types(state: &AppState) -> Result<Value, String> {
    state.client.get_goods_list_types().await
}

pub async fn get_goods_list(
    state: &AppState,
    uid: String,
    goods_id: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_goods_list(&uid, &goods_id, page).await
}

pub async fn get_goods_store_items(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_goods_store_items(&uid, page).await
}

pub async fn get_product_albums(
    state: &AppState,
    uid: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_product_albums(&uid, page).await
}

pub async fn get_my_goods_feeds(
    state: &AppState,
    uid: String,
    goods_type: String,
    page: u32,
) -> Result<Value, String> {
    state.client.get_my_goods_feeds(&uid, &goods_type, page).await
}

pub async fn create_goods_list(
    state: &AppState,
    title: String,
    message: String,
    cover: String,
    top_limit: u32,
    is_open_vote: u32,
    list_type: String,
    target_id: String,
    target_type: String,
) -> Result<Value, String> {
    state
        .client
        .create_goods_list(
            &title,
            &message,
            &cover,
            top_limit,
            is_open_vote,
            &list_type,
            &target_id,
            &target_type,
        )
        .await
}

pub async fn edit_goods_list(
    state: &AppState,
    id: String,
    title: String,
    message: String,
    cover: String,
    top_limit: u32,
    is_open_vote: u32,
    list_type: String,
) -> Result<Value, String> {
    state
        .client
        .edit_goods_list(&id, &title, &message, &cover, top_limit, is_open_vote, &list_type)
        .await
}

pub async fn add_goods_to_goods_list(
    state: &AppState,
    feed_id: String,
    goods_id: String,
    note: String,
    pic: String,
) -> Result<Value, String> {
    state
        .client
        .add_goods_to_goods_list(&feed_id, &goods_id, &note, &pic)
        .await
}

pub async fn delete_goods_list_items(
    state: &AppState,
    cancel_feed_id: String,
    goods_id: String,
) -> Result<Value, String> {
    state
        .client
        .delete_goods_list_items(&cancel_feed_id, &goods_id)
        .await
}

pub async fn edit_goods_list_item(
    state: &AppState,
    feed_id: String,
    goods_id: String,
    note: String,
    pic: String,
) -> Result<Value, String> {
    state
        .client
        .edit_goods_list_item(&feed_id, &goods_id, &note, &pic)
        .await
}

pub async fn vote_goods_list_item(
    state: &AppState,
    id: String,
    item_id: String,
    value: i32,
) -> Result<Value, String> {
    state.client.vote_goods_list_item(&id, &item_id, value).await
}

pub async fn bind_feed_to_goods_list(
    state: &AppState,
    feed_id: String,
    goods_list_id: String,
) -> Result<Value, String> {
    state
        .client
        .bind_feed_to_goods_list(&feed_id, &goods_list_id)
        .await
}

pub async fn upload_publish_video(state: &AppState, video_bytes: Vec<u8>, file_name: String, cover_bytes: Vec<u8>, duration: u64) -> Result<Value, String> {
    state.client.upload_publish_video(&video_bytes, &file_name, &cover_bytes, duration).await
}
